# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
MAILER_HOST: "rc.mywebsite.com"
S3_BUCKET_NAME: "test-images.ampersports.com"
AWS_ACCESS_KEY_ID: "AKIAIRL6COFAOB2EOC4Q"
AWS_SECRET_ACCESS_KEY: "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"
SECRET_KEY: "sk_test_2u3zhIoGjAGgR18YwA5D9cbs"
PUBLISHABLE_KEY: "pk_test_ytIXdyTkxYFJo5uDpUtiBXrn"
SENDGRID_USERNAME: "ampersports"
SENDGRID_PASSWORD: "HCkH9dsXigxWG8"
SENDGRID_DOMAIN: "ampersports.com"